package com.miguelcr.a01_localdatabase.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STUDENTS".
 */
@Entity
public class Students {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Integer age;
    private Boolean repeat;
    private Long idSubject;

    @Generated
    public Students() {
    }

    public Students(Long id) {
        this.id = id;
    }

    @Generated
    public Students(Long id, String name, Integer age, Boolean repeat, Long idSubject) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.repeat = repeat;
        this.idSubject = idSubject;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Boolean getRepeat() {
        return repeat;
    }

    public void setRepeat(Boolean repeat) {
        this.repeat = repeat;
    }

    public Long getIdSubject() {
        return idSubject;
    }

    public void setIdSubject(Long idSubject) {
        this.idSubject = idSubject;
    }

}
