package com.miguelcr.a01_localdatabase.localdb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUBJECTS".
 */
@Entity
public class Subjects {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String name;

    @Generated
    public Subjects() {
    }

    public Subjects(Long id) {
        this.id = id;
    }

    @Generated
    public Subjects(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

}
